-- MySQL Script generated by MySQL Workbench
-- Fri Jun 10 12:08:39 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema salao
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema salao
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `salao` DEFAULT CHARACTER SET utf8 ;
USE `salao` ;

-- -----------------------------------------------------
-- Table `salao`.`salao`
-- -----------------------------------------------------
CREATE TABLE `salao` (
  `id_cliente` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(220) NOT NULL,
  `telefone` VARCHAR(220) NOT NULL,
  `endereco` VARCHAR(220) NOT NULL,
  `agendamento` VARCHAR(220) NOT NULL,
  `horas` TIME NOT NULL,
  `procedimento` VARCHAR(220) NOT NULL,
  PRIMARY KEY (`id_cliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `salao`.`salao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `salao`.`salao` (
  `id_cliente` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(220) NOT NULL,
  `telefone` VARCHAR(220) NOT NULL,
  `endereco` VARCHAR(220) NOT NULL,
  `agendamento` VARCHAR(220) NOT NULL,
  `horas` TIME NOT NULL,
  `procedimento` VARCHAR(220) NOT NULL,
  PRIMARY KEY (`id_cliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `salao`.`atendente`
-- -----------------------------------------------------
CREATE TABLE `atendente` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(220) NOT NULL,
  `telefone` VARCHAR(220) NOT NULL,
  `endereco` VARCHAR(220) NOT NULL,
  `cpf` VARCHAR(220) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `salao`.`agenda`
-- -----------------------------------------------------
CREATE TABLE `agenda` (
  `salao_id` INT NOT NULL,
  `atendente_id` INT NOT NULL,
  `nome_cliente` VARCHAR(220) NOT NULL,
  `data_agendamento` DATE NOT NULL,
  `procedimento` VARCHAR(220) NOT NULL,
  `atendente` VARCHAR(220) NOT NULL,
  `hora_agendamento` TIME NOT NULL,
  PRIMARY KEY (`salao_id`, `atendente_id`),
  INDEX `fk_salao_has_atendente_atendente1_idx` (`atendente_id` ASC),
  INDEX `fk_salao_has_atendente_salao_idx` (`salao_id` ASC),
  CONSTRAINT `fk_salao_has_atendente_salao`
    FOREIGN KEY (`salao_id`)
    REFERENCES `salao`.`salao` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_salao_has_atendente_atendente1`
    FOREIGN KEY (`atendente_id`)
    REFERENCES `salao`.`atendente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
